== Concepts


The main concepts are: paragraph, paragraph context, and paragraph renderer.


=== Anatomy of a paragraph

The figure below shows all spacing characteristics of a paragraph.
The outer rectangle (using `+`, `-`, and `|` characters) marks the most outer part of a paragraph.
This is followed by top, bottom, left, and right frame margins.

The next rectangle (using the UTF-8 double line characters `╔`, `═`, `╗`, `╚`, `║`, and `╝`) shows an example frame.
This is followed by top / bottom text margins and left / right string margins.

Left and right we find the start and end strings that can be set. This is followed by the left / right text margins.

The last rectangle (using the single line UTF-8 characters `┌`, `─`, `┐`, `└`, `─`, and `┘`) marks the actual paragraph.
Here we have the text, plus optional padding and indentations.

----
+----------------------------------------------------------------------------------------------+
|                                                                                              |
|                                      Top Frame Margin                                        |
|                                                                                              |
|--------╔════════════════════════════════════════════════════════════════════════════╗--------|
|        ║                                                                            ║        |
|        ║                             Top Text Margin                                ║        |
|        ║                                                                            ║        |
|        ║--------+--------+--------┌─────────────────────┐--------+--------+---------║        |
|        ║        |        |        │                     │        |        |         ║        |
|  F  M  ║  S  M  |  S  S  |  T  M  │      Paragraph      │  T  M  |  E  S  |  S   M  ║  F  M  |
|  r  a  ║  t  a  |  t  t  |  e  a  │      text with      │  e  a  |  n  t  |  t   a  ║  r  a  |
|  a  r  ║  r  r  |  a  r  |  x  r  │      padding &      │  x  r  |  d  r  |  r   r  ║  a  r  |
|  m  g  ║  i  g  |  r  i  |  t  g  │     indentation     │  t  g  |     i  |  i   g  ║  m  g  |
|  e  i  ║  n  i  |  t  g  |     i  │                     │     i  |     g  |  n   i  ║  e  i  |
|     n  ║  g  n  |        |     n  │                     │     n  |        |  g   n  ║     n  |
|        ║        |        |        │                     │        |        |         ║        |
|        ║--------+--------+--------└─────────────────────┘--------+--------+---------║        |
|        ║                                                                            ║        |
|        ║                            Bottom Text Margin                              ║        |
|        ║                                                                            ║        |
|--------╚════════════════════════════════════════════════════════════════════════════╝--------|
|                                                                                              |
|                                     Bottom Frame Margin                                      |
|                                                                                              |
+----------------------------------------------------------------------------------------------+
----


=== Paragraph details

A paragraph is a collection of text strings.
The strings are processed as follows:

* add text to the paragraph, multiple times if required
* the paragraph will separate each added text using a space
* for rendering a paragraph, all excessive white spaces will be removed
  ** tabulators (converted to spaces),
  ** more than one consecutive space,
  ** line feed,
  ** carriage return, and
  ** line feed and carriage return.

==== Format of a paragraph

Paragraphs can be formatted using a number of special formats.
Currently implemented are

* First line - an indentation for the first line of the paragraph
* Hanging paragraph - an indentation for everything but the first line
* Dropped capital letter - a large capital letter for the first character of the first sentence spanning multiple lines


==== Text alignment

Text in the paragraph can be aligned in multiple different ways:

* align left (open ended right site)
* align right (open ended left site)
* centered (all lines centered)
* justified (all line justified)
* justified with last line left aligned
* justified with last line right aligned 


==== Text padding

All lines will use padding to create a paragraph with equal length of each line.
The padding on the left and the right depends on the text alignment:

- align left: no padding left (all lines bound), padding on the right
- align right: no padding on the right (all lines bound), padding on the right
- centered: padding on both sides of each line
- justified: no padding at all, each line starts and finishes with a word (or single character)
- justified last line left align: padding only for the last line, on the right site
- justified last line right align: padding only for the last line, on the left site

The characters being used for padding can be set separately, so that each site of a line gets a different padding character.


==== In-text white spaces

With all excessive white spaces removed, each line only contains single blanks.
The exception to this rule are all justified paragraphs (here extra white spaces are added to give the impression of a justified paragraph).

The implementation allows to change the character used for in-text white spaces from the default (a blank) to any other character.


==== Start and end strings

Each line of a paragraph can be started and terminated by a specific (different or identical) string.
These strings are outside the text area, i.e. no special formatting is done on those strings.


==== Margins

A paragraph has several margins for the left and right sides as well as for top and bottom.
Each margin can be set - the width for let/right side margins and the height for top and bottom margins.
Additionally, a character can be set for left/right margins (the same or different characters for each side).


==== Frame

A paragraph can also be framed. A frame is

* a line above the paragraph,
* borders for each line of the paragraph (on the left and right side),
* and a line at the bottom of of the paragraph.

The frame is set as a frame theme.
A number of those themes are provided in the `skb-interfaces` package.
New themes can be created very easily, using ASCII and/or UTF-8 characters.


=== Summary of configurable  characteristics

- text width (length of each text line)
- text alignment (for the whole paragraph): left, right, centered, justified (with additional options for last line)
- text format: first line, hanging, dropped capital letter
- frame: set a frame around the paragraph
- start / end string: define a start and/or end string for each line
- top and bottom margins above a frame (empty lines)
- margins on the left and right of a frame (number with character)
- margins between the frame and the start string (left) and end string and frame (right), using different length and character
- margins between start string and text (left), and text and end string (right), using different length and characters
- top and bottom margins for the text (including and string margin and string)
- character converters to convert characters before line generation, i.e. to generate text suitable for LaTeX or HTML


=== Paragraph Context

While the paragraph only maintains the text, the paragraph context maintains all configurable characteristics of the paragraph (see above).
The current implementation directly has

* paragraph alignment (default being justified, last line left)
* paragraph format (default being none)
* paragraph width (default being 80)
* an optional library for dropped capital letters (default being not set)
* an optional theme for a frame (default being not set)

The following characteristics are handled by special objects (one for each), which the context provides access to:

* indentations (for first line and hanging paragraph)
* all margins
* all characters
* all strings
* all character (and target) translators

Additionally, the context provides a number of helper methods for rendering

* different calculations for width, starting with simple text width and finishing with an all inclusive width
* convenience methods to jointly set margins and characters, for the same left/right or top/bottom pairs

The paragraph can be initialized with a given context or plain, in which case it will create its own context object.
Any future characteristics will be added to the paragraph context


=== Paragraph Renderer

The actual rendering of a paragraph is realized by special render objects (i.e. it's not done in the paragraph or its context).
A paragraph can be rendered in two different ways:

. call the provided render methods on the paragraph object itself
. use a specialized render object

No changes are made to the paragraph text or any context settings by any render operation.
All required text being processed and calculations being made will happen inside the renderer.

The render methods on the paragraph allow to render it (a) to the width set in the context or (b) to an overall required width.
The first option is the most simple one: fill paragraph with text, set width on context, render.
The second option can be used by other applications, for instance a table, to get a paragraph of required width.

For any other render operations use the provided standard renderer or create your own render object.
The default renderer does currently provide render methods to different width with calculations provided by the context.

Note: coming soon: 
It also provides render methods that use their own context (i.e. ignore the context set in the paragraph).
This allows for extremely flexibility in using the paragraph in many different scenarios.

